name: visual_1
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: "3.3.8"

dependencies:
  flutter:
    sdk: flutter
  iconify_flutter: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Gilmer
      fonts:
        - asset: assets/fonts/gilmer/gilmer-light.otf
          weight: 300
        - asset: assets/fonts/gilmer/gilmer-regular.otf
          weight: 400
        - asset: assets/fonts/gilmer/gilmer-heavy.otf
          weight: 800
        - asset: assets/fonts/gilmer/gilmer-medium.otf
          weight: 600
        - asset: assets/fonts/gilmer/gilmer-bold.otf
          weight: 700
        - asset: assets/fonts/gilmer/gilmer-outline.otf
          weight: 800
