name: firebase_login
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.0
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  font_awesome_flutter: ^9.2.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  google_fonts: ^2.1.0
  #meta: ^1.3.0
  #very_good_analysis: ^2.3.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  