name: meta_weather_api
description: A Dart API Client for the MetaWeather API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.1.4
  coverage: ^1.0.3
  json_serializable: ^6.0.1
  mocktail: ^0.2.0
  test: ^1.19.2
