name: contact_list_app
description: Contact list for create online/offline synchronization.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dio: ^5.1.2
  equatable: ^2.0.5
  file_picker: ^5.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.0
  flutter_secure_storage: ^8.0.0
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  open_filex: ^4.3.2
  sqflite: ^2.2.8+4
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
