name: google_maps_sample
description: Flutter project to test google maps API.

publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.11

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true