name: form_inputs
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  formz: ^0.4.1

dev_dependencies:
  flutter_lints: ^1.0.4
