name: masterclass
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  provider: ^5.0.0


dev_dependencies:
  build_runner: ^2.0.6 # necessitam por causa da geração de código para o mobx
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mobx_codegen: ^2.0.1+3 # necessitam por causa da geração de código para o mobx

flutter:
  uses-material-design: true