name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  #cache:
  #  path: ../cache
  equatable: ^2.0.3
  fireauth: ^0.9.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.1
  #meta: ^1.3.0
  #very_good_analysis: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
