name: shopping_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'

dependency:
dependencies: 
  equatable: ^2.0.3
  flutter: 
    sdk: flutter
  