name: person_form
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  camera: ^0.9.4+3
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  formz: ^0.4.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  path: ^1.8.0
  path_provider: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
