include: package:lint/analysis_options.yaml

# Not happy with the default? Customize the rules depending on your needs. 
# Here are some examples:
linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    always_specify_types: true
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false