name: login
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  formz: ^0.4.1
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^8.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true
