name: flutter_cookbook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

  # precisa para utilizar o sqlite
  sqflite:
  path:

  # precisa para utilizar files
  path_provider: ^2.0.2

  # precisa para utilizar o NSUserDefaults on iOS and SharedPreferences on Android 
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Qahiri
      fonts:
        - asset: assets/fonts/Qahiri-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
  assets:
    - assets/images/cat-5855647_1920.jpg
  uses-material-design: true
