name: manguinho
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  provider: ^6.0.2

dev_dependencies:
  faker: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/

flutter_icons:
  android: true
  image_path: 'lib/ui/assets/icons/android.png'
  adaptive_icon_background: 'lib/ui/assets/icons/background.png'
  adaptive_icon_foreground: 'lib/ui/assets/icons/foreground.png'