name: contact_list_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.3.0
  equatable: ^2.0.5
  shelf: ^1.4.0
  shelf_multipart: ^1.0.0
  shelf_router: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  http: ^0.13.0
  lints: ^2.1.0
  test: ^1.21.0
