name: sandbox
description: "Sandbox for simple flutter projects."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: "3.32.7"

dependencies:
  flutter: #                    # all
    sdk: flutter

dev_dependencies:
  flutter_test: #               # all
    sdk: flutter
  flutter_lints: "6.0.0" #      # all

flutter:
  uses-material-design: true
