name: products
description: List products.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_rating_bar: ^4.0.0
  get_it: ^7.2.0
  image_picker: ^0.8.4+4
  path: ^1.8.0
  path_provider: ^2.0.8
  select_form_field: ^2.2.0

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/database/