import '../../entities/entities.dart';

final contactsDB = <Contact>[
  // Contact(
  //   id: const Uuid().v4(),
  //   name: 'Jão (normal)',
  //   avatarUrl: 'https://archives.bulbagarden.net/media/upload/5/54/0007Squirtle.png',
  //   documentUrl: 'https://www.orimi.com/pdf-test.pdf',
  //   createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 12)),
  // ),
  // Contact(
  //   id: const Uuid().v4(),
  //   name: 'Maria (vazio)',
  //   avatarUrl: '',
  //   documentUrl: '',
  //   createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 12)),
  // ),
  // Contact(
  //   id: const Uuid().v4(),
  //   name: 'Maria (urls bugados)',
  //   avatarUrl: 'https://pixabay.com/get/gf62d964c9db4324cbaee_640.png',
  //   documentUrl: 'https://google.com/asd.png',
  //   createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 12)),
  // ),
  // Contact(id: const Uuid().v4(), name: '4', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '5', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '6', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '7', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '8', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '9', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '10', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '11', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '12', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '13', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '14', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '15', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '16', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '17', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '18', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '19', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '20', avatarUrl: '', documentUrl: ''),
  // Contact(id: const Uuid().v4(), name: '21', avatarUrl: '', documentUrl: ''),
];
